[versions]
jspecify = "1.0.0"
guava = "25.1-jre" # Matches dependency from Velocity
oshi = "6.9.0" # Matches dependency from Paper
flare = "4.0.9"
folia-api = "1.21.11-R0.1-SNAPSHOT"
velocity-api = "3.4.0-SNAPSHOT"
shadow = "9.2.2"
lombok = "8.13.1"
run-task = "3.0.2"
blossom = "2.1.0"
resource-factory = "1.3.1"
config-api = "1.2.7"
configurate4 = "4.1.2" # Matches velocity

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
flare = { module = "net.serlith:Flare", version.ref = "flare" }
folia-api = { module = "dev.folia:folia-api", version.ref = "folia-api" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }
configurate4-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate4" }
config-api-core = { module = "net.serlith.ConfigAPI:ConfigAPI-core", version.ref = "config-api" }
config-api-adventure = { module = "net.serlith.ConfigAPI:ConfigAPI-adventure", version.ref = "config-api" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run-task" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
resource-factory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resource-factory" }
resource-factory-velocity = { id = "xyz.jpenilla.resource-factory-velocity-convention", version.ref = "resource-factory" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
