[versions]
jspecify = "1.0.0"
guava = "25.1-jre" # Matches dependency from Velocity
oshi = "6.6.5" # Matches dependency from Paper
flare = "4.0.9"
folia-api = "1.21.8-R0.1-SNAPSHOT"
velocity-api = "3.4.0-SNAPSHOT"
run-task = "3.0.2"
resource-factory = "1.3.1"
configurate4 = "4.1.2" # Matches velocity

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
flare = { module = "net.serlith:Flare", version.ref = "flare" }
folia-api = { module = "dev.folia:folia-api", version.ref = "folia-api" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }
configurate4-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate4" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
